SELECT EMPLOYEE.EMP_NUM, EMPLOYEE.EMP_LNAME,
EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_INITIAL, PROJECT.PROJ_NAME,
PROJECT.PROJ_VALUE, PROJECT.PROJ_BALANCE, JOB.JOB_CODE,
JOB.JOB_DESCRIPTION, JOB.JOB_CHG_HOUR
FROM EMPLOYEE
JOIN JOB ON EMPLOYEE.JOB_CODE = JOB.JOB_CODE
JOIN PROJECT ON EMPLOYEE.EMP_NUM = PROJECT.EMP_NUM
ORDER BY PROJECT.PROJ_VALUE; 