SELECT LGEMPLOYEE.EMP_NUM, LGEMPLOYEE.EMP_LNAME, 
LGEMPLOYEE.EMP_FNAME, LGSALARY_HISTORY.SAL_FROM,
LGSALARY_HISTORY.SAL_END, LGSALARY_HISTORY.SAL_AMOUNT
FROM LGEMPLOYEE
JOIN LGSALARY_HISTORY 
ON LGEMPLOYEE.EMP_NUM = LGSALARY_HISTORY.EMP_NUM
WHERE LGEMPLOYEE.EMP_NUM IN (83731, 83745, 84039)
ORDER BY LGEMPLOYEE.EMP_NUM, LGSALARY_HISTORY.SAL_FROM;