SELECT LGEMPLOYEE.EMP_NUM, LGEMPLOYEE.EMP_LNAME, LGEMPLOYEE.EMP_FNAME, SAL_AMOUNT
FROM LGEMPLOYEE
JOIN (
    SELECT EMP_NUM, MIN(LGSALARY_HISTORY.SAL_FROM) AS min_start_date
    FROM LGSALARY_HISTORY
    GROUP BY EMP_NUM
) AS min_dates ON LGEMPLOYEE.EMP_NUM = min_dates.EMP_NUM
JOIN LGSALARY_HISTORY ON LGEMPLOYEE.EMP_NUM = LGSALARY_HISTORY.EMP_NUM AND LGSALARY_HISTORY.SAL_FROM = min_dates.min_start_date
ORDER BY  LGEMPLOYEE.EMP_NUM;