SELECT EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_EMAIL,
SUM(LGLINE.LINE_QTY) AS total_units_sold
FROM LGEMPLOYEE
JOIN LGINVOICE ON LGEMPLOYEE.EMP_NUM = LGINVOICE.EMPLOYEE_ID
JOIN LGLINE ON LGINVOICE.INV_NUM = LGLINE.INV_NUM
JOIN LGPRODUCT ON LGLINE.PROD_SKU = LGPRODUCT.PROD_SKU
JOIN LGBRAND ON LGPRODUCT.BRAND_ID = LGBRAND.BRAND_ID
WHERE LGBRAND.BRAND_NAME = 'Binder Prime'
AND INV_DATE >= '2017-11-01' AND INV_DATE <= '2017-12-05'
GROUP BY EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_EMAIL
ORDER BY total_units_sold DESC, EMP_LNAME ASC
LIMIT 2;