SELECT LGPRODUCT.BRAND_ID, LGBRAND.BRAND_NAME, 
LGBRAND.BRAND_TYPE,  FORMAT(avg_price, 2) AS average_price
FROM (
    SELECT BRAND_ID, AVG(PROD_PRICE) AS avg_price
    FROM LGPRODUCT
    GROUP BY BRAND_ID 
) AS max_avg_price
JOIN LGBRAND ON max_avg_price.BRAND_ID = LGBRAND.BRAND_ID
JOIN LGPRODUCT ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
ORDER BY avg_price DESC
LIMIT 1;