SELECT
    FORMAT(SUM(CUS_BALANCE), 2) AS "Total Balance",
    FORMAT(MIN(CUS_BALANCE), 2) AS "Minimum Balance",
    FORMAT(MAX(CUS_BALANCE), 2) AS "Maximum Balance",
    FORMAT(AVG(CUS_BALANCE), 2) AS "Average Balance"
FROM CUSTOMER
LEFT JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
WHERE INVOICE.CUS_CODE IS NULL