SELECT
    FORMAT(MIN(CUS_BALANCE), 2) AS "Minimum Balance",
    FORMAT(MAX(CUS_BALANCE), 2) AS "Maximum Balance",
    FORMAT(AVG(CUS_BALANCE), 2) AS "Average Balance"
FROM (
SELECT CUS_BALANCE
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
GROUP BY CUSTOMER.CUS_CODE, CUSTOMER.CUS_BALANCE
) AS SUBQUERY