SELECT ASSIGNMENT.ASSIGN_NUM, ASSIGNMENT.EMP_NUM,
ASSIGNMENT.PROJ_NUM, ASSIGNMENT.ASSIGN_CHARGE, 
(ASSIGNMENT.ASSIGN_CHG_HR * ASSIGNMENT.ASSIGN_HOURS)
AS CALC_ASSIGN_CHG
FROM ASSIGNMENT
ORDER BY ASSIGNMENT.ASSIGN_NUM;