SELECT CUSTOMER.CUS_CODE, INVOICE.INV_NUMBER, 
PRODUCT.P_DESCRIPT, LINE.LINE_UNITS AS "Units Bought",
LINE.LINE_PRICE AS "Unit Price",
(LINE.LINE_UNITS * LINE.LINE_PRICE) AS "Subtotal" FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE
ORDER BY CUSTOMER.CUS_CODE, INVOICE.INV_NUMBER, 
PRODUCT.P_DESCRIPT;