SELECT BOOK.BOOK_NUM, BOOK.BOOK_TITLE,
COUNT(CHECKOUT.BOOK_NUM) AS "Times Checked Out"
FROM BOOK
LEFT JOIN CHECKOUT ON BOOK.BOOK_NUM = CHECKOUT.BOOK_NUM
GROUP BY BOOK_NUM, BOOK_TITLE
HAVING COUNT(CHECKOUT.BOOK_NUM) > 5
ORDER BY COUNT(CHECKOUT.BOOK_NUM) DESC, BOOK_TITLE;