CREATE TABLE question (
QUESTION_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
QUESTION VARCHAR(100) NOT NULL,
CHOICE_1 VARCHAR(100) NOT NULL,
CHOICE_2 VARCHAR(100) NOT NULL,
CHOICE_3 VARCHAR(100) NOT NULL,
CHOICE_4 VARCHAR(100) NOT NULL,
CORRECT_CHOICE VARCHAR(100) NOT NULL,
SONG_NAME VARCHAR(100) NOT NULL,
ARTIST_NAME VARCHAR(100) NOT NULL,
IMAGE_PATH VARCHAR(100) NOT NULL,
PRIMARY KEY(QUESTION_ID)
);

CREATE TABLE scores (
SCORE_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
PLAYER_NAME VARCHAR(100) NOT NULL,
PLAYER_SCORE FLOAT NOT NULL,
PRIMARY KEY(SCORE_ID)
);